FROM node:12.6.0 as builder

RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY ../../package.json /usr/src/app/package.json
COPY ../../package-lock.json /usr/src/app/package-lock.json
RUN npx npm-force-resolutions
RUN npm install

COPY . /usr/src/app
RUN npm run build:web:prod

FROM nginx:1.17.5
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /usr/src/app/dist/fr-admin-app /usr/share/nginx/html
COPY nginx.tmpl /etc/nginx/nginx.tmpl
EXPOSE 80 443

CMD ["/bin/sh",  "-c",  "envsubst '$API_PATH,$WS_PATH' < /etc/nginx/nginx.tmpl > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"]
